Kyle's Doxygen Test: src/utility.hpp File Reference
utility.hpp File Reference
Macros
#define MAGIC_NUMBER 1337
Magic number for magical computation.
Five Gods constants.
#define MEW2KING 1
Five Gods constants.
#define ARMADA 2
Five Gods constants.
#define HUNGRYBOX 3
Five Gods constants.
#define MANGO 4
Five Gods constants.
#define PPMD 5
Five Gods constants.
Functions
int square (int x)
Squares a number.
int multiply (int x, int y)
Multiplies two numbers.
int magic (int x)
Function for magic math.
int battleOfTheFiveGods ()
Multiplies all the gods together.
Macro Definition Documentation
ARMADA
#define ARMADA 2
Five Gods constants.
These five constants represent the five gods.
Definition at line 21 of file utility.hpp.
HUNGRYBOX
#define HUNGRYBOX 3
Five Gods constants.
These five constants represent the five gods.
Definition at line 22 of file utility.hpp.
MAGIC_NUMBER
#define MAGIC_NUMBER 1337
Magic number for magical computation.
This number is selected to be the most elite number there is. No other numbers are more elite than this number.
Definition at line 10 of file utility.hpp.
MANGO
#define MANGO 4
Five Gods constants.
These five constants represent the five gods.
Definition at line 23 of file utility.hpp.
MEW2KING
#define MEW2KING 1
Five Gods constants.
These five constants represent the five gods.
Definition at line 20 of file utility.hpp.
PPMD
#define PPMD 5
Five Gods constants.
These five constants represent the five gods.
Definition at line 24 of file utility.hpp.
Function Documentation
battleOfTheFiveGods()
int battleOfTheFiveGods ()
Multiplies all the gods together.
This function just multiplies the five god constants together.
Returns
The product of the five numbers.
Definition at line 15 of file utility.cpp.
{
    return MEW2KING * ARMADA * HUNGRYBOX * MANGO * PPMD;
}
References ARMADA, HUNGRYBOX, MANGO, MEW2KING, and PPMD.
Referenced by testNumbers().
magic()
int magic (int x)
Function for magic math.
This function multiplies a number by the magic number.
Parameters
x The number on which to perfom magic.
Returns
The magic product of the number.
Definition at line 11 of file utility.cpp.
                 {
    return MAGIC_NUMBER * x;
}
References MAGIC_NUMBER.
Referenced by testNumbers().
multiply()
int multiply (int x, int y)
Multiplies two numbers.
This function multiplies a number times another number and returns the result of those two numbers multiplied together. The result is the product of the two numbers, and that is the value that is returned by this function.
Parameters
x The first operand.
y The second operand.
Returns
The product of x and y.
Definition at line 7 of file utility.cpp.
{
    return x * y;
}
Referenced by Dog::run(), Dog::sleep(), and testNumbers().
square()
int square (int x)
Squares a number.
This function multiplies a given number by itself, which results in the square of that number.
Parameters
x The number to square.
Returns
The square of the number.
Definition at line 3 of file utility.cpp.
                  {
    return x * x;
}
Referenced by testNumbers().